---
- hosts: all
  gather_facts: yes
  tasks:
    - name: TASK 01 - Get current Date
      command: date
      register: current_date
      changed_when: false

    - name: TASK 02 - Print current Time Zone
      debug:
        msg: "{{ current_date.stdout  }}"
...
